apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: 3-tier-app-eks
spec:
  type: ExternalName
  externalName: my-postgres-db.cn6kaos6emcz.us-west-2.rds.amazonaws.com
  ports:
    - port: 5432
