apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: 3-tier-app-eks
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: null  # <--- don't auto-delete the pod
  template:
    spec:
      containers:
        - name: migrate
          image: livingdevopswithakhilesh/devopsdozo:backend-latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              flask db init || true && \
              flask db migrate -m "init" && \
              flask db upgrade
          env:
            - name: FLASK_APP
              value: run.py
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_URL
      restartPolicy: Never
